name: Sync labels

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Sync labels
        uses: brpaz/action-label-syncer@32e516ae73bbf7c7c0548897be07080795336e15 # 0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
